# Project Information
site_name: blog
site_description: 随便搭建的博客，写一些平时的做题总结等
site_author: plextem
site_url: 
strict: true

# Repository
repo_name: 'plextem/blog'
repo_url: 'https://github.com/plextem/blog'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2018 - 2018 plextem'

# Contents
nav:
  - 首页: index.md
  - 专题总结:
    - 分数规划: articles/fractional-programming/fp.md
    - 网络流24题总结: 
      - 1.飞行员配对方案问题: articles/NetWork24/1.md
      - 2.太空飞行计划问题: articles/NetWork24/2.md
      - 3.最小路径覆盖问题: articles/NetWork24/3.md
      - 4.魔术球问题: articles/NetWork24/4.md
      - 5.圆桌问题: articles/NetWork24/5.md           
      - 6.最长不下降子序列问题: articles/NetWork24/6.md     
      - 7.试题库问题: articles/NetWork24/7.md          
      - 8.机器人路径规划问题: articles/NetWork24/8.md    
      - 9.方格取数问题: articles/NetWork24/9.md         
      - 10.餐巾计划问题: articles/NetWork24/10.md       
      - 11.航空路线问题: articles/NetWork24/11.md       
      - 12.软件补丁问题: articles/NetWork24/12.md       
      - 13.星际转移问题: articles/NetWork24/13.md       
      - 14.孤岛营救问题: articles/NetWork24/14.md       
      - 15.汽车加油问题: articles/NetWork24/15.md       
      - 16.数字梯形问题: articles/NetWork24/16.md       
      - 17.运输问题: articles/NetWork24/17.md         
      - 18.分配问题: articles/NetWork24/18.md         
      - 19.负载平衡问题: articles/NetWork24/19.md       
      - 20.深海机器人问题: articles/NetWork24/20.md      
      - 21.最长k可重区间集问题: articles/NetWork24/21.md   
      - 22.最长k可重线段集问题: articles/NetWork24/22.md   
      - 23.火星探险问题: articles/NetWork24/23.md       
      - 24.骑士共存问题: articles/NetWork24/24.md
  - 做题记录:
    - BZOJ:
      - 1053 反素数: prac/bzoj/bz1053.md
      - 1060 时态同步: prac/bzoj/bz1060.md
      - 1087 互不侵犯: prac/bzoj/bz1087.md
      - 1565 植物大战僵尸: prac/bzoj/bz1565.md
      - 3668 起床困难综合症: prac/bzoj/bz3668.md
      - 4720 换教室: prac/bzoj/bz4720.md
      - 4800 世界冰球锦标赛: prac/bzoj/bz4800.md
    - luogu:
      - 1084 疫情控制: prac/luogu/luogu1084.md
      - 1967 货车运输: prac/luogu/luogu1967.md
      - 2680 运输计划: prac/luogu/luogu2680.md    
      - 2831 愤怒的小鸟: prac/luogu/luogu2831.md
      - 3953 逛公园: prac/luogu/luogu3953.md
    - atcoder:
      - agc028 Removing Blocks: prac/atcoder/agc028_b.md
  - 友链: links.md
  
theme:
  name: 'material'
  # custom_dir: 'custom_theme'
  static_templates:
    - 404.html
  language: 'zh'
  logo:
    icon: 'all_inclusive'
  palette:
    primary: 'blue'
    accent: 'red'
  feature:
    tabs: true
  search_index_only: true
  # font:
    # text: 'Fira Sans'
    # code: 'Fira Mono'

# Customization
extra:
  search:
    language: 'zh'
  copyright: 'CC BY-SA 4.0'
  pagetime: 'on'

extra_javascript:
  - '_static/js/extra.js?v=2'
  - 'https://cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'
  # - //cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - '_static/css/extra.css?v=2'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - mdx_math
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

remote_branch: gh-pages